# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20180613_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pass_key',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
