# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_course_pass_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
